# some linters don't work with generics, golangci-lint disable those linters automatically with go1.18.
# follow https://github.com/golangci/golangci-lint/issues/2649
run:
  go: '1.17'
  timeout: 5m

  # Timeout for analysis, Default: 1m
  timeout: 5m
