# some linters don't work with generics, golangci-lint disable those linters automatically with go1.18.
# follow https://github.com/golangci/golangci-lint/issues/2649
run:
  go: '1.17'
  timeout: 5m
linters:
  disable:
    - structcheck # This linter is abandoned, with the last update several years ago.
