# TODO: Change the Coverage Target in future.

coverage:
  status:
    patch: off
    project:
      default: # This can be anything, but it needs to exist as the name
        # basic settings
        target: 69
        threshold: 2% # Raise exception if it drops lower by 2% (e.g. 94% coverage to 92%)

ignore:
  - pkg/testingutil
