types:
  - name: Instance
    listApi:
      call: DescribeInstances
      inputOverrides:
        fieldFuncs:
          Filters: describeInstancesFilters
      pagination: true
      outputKey: [Reservations, Instances]
      id: InstanceId
      tags: &tags
        field: Tags
        key: Key
        value: Value
  - name: Volume
    listApi:
      call: DescribeVolumes
      pagination: true
      outputKey: Volumes
      id: "VolumeId"
      tags: *tags
  - name: VPC
    listApi:
      call: DescribeVpcs
      pagination: true
      outputKey: Vpcs
      id: VpcId
      tags:
        field: Tags
        key: Key
        value: Value
