types:
  - name: Instance
    description: EC2 Instances
    listApi:
      call: DescribeInstances
      pagination: true
      outputKey: [Reservations, Instances]
      id: InstanceId
      tags:
        field: [Tags]
        key: Key
        value: Value
