types:
  - name: CacheCluster
    listApi:
      call: DescribeCacheClusters
      outputKey: CacheClusters
      id: ARN
      pagination: true
    getTagsApi:
      call: ListTagsForResource
      inputIDField:
        name: ResourceName
      tags:
        style: struct
        field: "TagList"
        pointer: true
        key: Key
        value: Value
    transformers:
      - displayIdArnPrefix("cluster:")
