global: true

types:
  - name: OpenIDConnectProvider
    listApi:
      call: ListOpenIDConnectProviders
      outputKey: OpenIDConnectProviderList
      id: Arn
    getTagsApi:
      call: ListOpenIDConnectProviderTags
      type: OpenIDConnectProviderListEntry
      inputIDField: OpenIDConnectProviderArn
      tags: &tags
        style: struct
        pointer: true
        field: Tags
        key: Key
        value: Value
  - name: Policy
    listApi:
      call: ListPolicies
      pagination: true
      inputOverrides:
        fieldFuncs:
          Scope: listPoliciesScope
      outputKey: Policies
      id: Arn
    getTagsApi:
      type: Policy
      call: ListPolicyTags
      inputIDField: PolicyArn
      tags: *tags
  - name: SAMLProvider
    listApi:
      call: ListSAMLProviders
      outputKey: SAMLProviderList
      id: Arn
    getTagsApi:
      call: ListSAMLProviderTags
      type: SAMLProviderListEntry
      inputIDField: SAMLProviderArn
      tags: *tags
  - name: VirtualMFADevice
    listApi:
      call: ListVirtualMFADevices
      pagination: true
      outputKey: VirtualMFADevices
      id: SerialNumber
    getTagsApi:
      type: VirtualMFADevice
      call: ListMFADeviceTags
      inputIDField: SerialNumber
      tags: *tags
