global: true

types:
  - name: OpenIDConnectProvider
    listApi:
      call: ListOpenIDConnectProviders
      outputKey: OpenIDConnectProviderList
      sdkType: OpenIDConnectProviderListEntry
      id: Arn
    getTagsApi:
      call: ListOpenIDConnectProviderTags
      inputIDField: OpenIDConnectProviderArn
      tags: &tags
        style: struct
        pointer: true
        field: Tags
        key: Key
        value: Value
  - name: Policy
    listApi:
      call: ListPolicies
      pagination: true
      inputOverrides:
        fieldFuncs:
          Scope: listPoliciesScope
      outputKey: Policies
      id: Arn
      displayId: PolicyName
    getTagsApi:
      call: ListPolicyTags
      inputIDField: PolicyArn
      tags: *tags
  - name: SAMLProvider
    listApi:
      call: ListSAMLProviders
      outputKey: SAMLProviderList
      sdkType: SAMLProviderListEntry
      id: Arn
    getTagsApi:
      call: ListSAMLProviderTags
      inputIDField: SAMLProviderArn
      tags: *tags
  - name: VirtualMFADevice
    listApi:
      call: ListVirtualMFADevices
      pagination: true
      outputKey: VirtualMFADevices
      id: SerialNumber
    getTagsApi:
      call: ListMFADeviceTags
      inputIDField: SerialNumber
      tags: *tags
