types:
  - name: Function
    listApi:
      call: ListFunctions
      pagination: true
      outputKey: Functions
      sdkType: FunctionConfiguration
      id: FunctionArn
      displayId: FunctionName
    getTagsApi:
      call: GetFunction
      inputIDField: FunctionName
      tags:
        style: map
        field: Tags
    transformers:
      - displayIdArnPrefix("function:")
