types:
  - name: DBInstance
    description: RDS DB Instances
    listApi:
      call: DescribeDBInstances
      pagination: true
      outputKey: [DBInstances]
      id: DBInstanceIdentifier
    tags:
      field: TagList
      key: Key
      value: Value
  - name: DBCluster
    description: RDS Auora DB Clusters
    listApi:
      call: DescribeDBClusters
      pagination: true
      outputKey: [DBClusters]
      id: DBClusterIdentifier
    tags:
      field: TagList
      key: Key
      value: Value
