types:
  - name: Topic
    listApi:
      call: ListTopics
      outputKey: Topics
      id: TopicArn
      sdkType: Topic
      pagination: true
    getTagsApi:
      call: ListTagsForResource
      inputIDField: ResourceArn
      tags:
        style: struct
        field: "Tags"
        pointer: true
        key: Key
        value: Value
