// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Item struct {
	ID          int    `json:"id"`
	OrderID     int    `json:"orderId"`
	ProductCode string `json:"productCode"`
	ProductName string `json:"productName"`
	Quantity    int    `json:"quantity"`
}

type ItemInput struct {
	ProductCode string `json:"productCode"`
	ProductName string `json:"productName"`
	Quantity    int    `json:"quantity"`
}

type NewResource struct {
	ID     string   `json:"id"`
	Region string   `json:"region"`
	Type   string   `json:"type"`
	Tags   []NewTag `json:"tags"`
}

type NewTag struct {
	ID    string `json:"id"`
	Key   string `json:"key"`
	Value string `json:"value"`
}

type NewUser struct {
	Name string `json:"name"`
}

type Order struct {
	ID           int     `json:"id"`
	CustomerName string  `json:"customerName"`
	OrderAmount  float64 `json:"orderAmount"`
	Items        []Item  `json:"items"`
}

type OrderInput struct {
	CustomerName string      `json:"customerName"`
	OrderAmount  float64     `json:"orderAmount"`
	Items        []ItemInput `json:"items"`
}

type Resource struct {
	ID     string `json:"id"`
	Region string `json:"region"`
	Type   string `json:"type"`
	Tags   []Tag  `json:"tags"`
}

type Tag struct {
	ID         string `json:"id"`
	ResourceID int    `json:"resourceId"`
	Key        string `json:"key"`
	Value      string `json:"value"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
