
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prod-cluster
  region: us-east-1
  tags:
    env: prod
    team: marketplace
    market: North America
    cluster: prod-cluster

privateCluster:
  enabled: true

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    privateNetworking: true
    tags:
      env: prod
      team: marketplace
      market: North America
      cluster: prod-cluster


