# This config represents all the user-configurable settings for cloudgrep and their default values
# https://github.com/run-x/cloudgrep/blob/main/pkg/config/config.yaml

# web represents the specs cloudgrep uses for creating the webapp server
web:
  # host is the host the server is running as
  host: localhost
  # port is the port the server is running in
  port: 8080
  # prefix is the url prefix the server uses
  prefix: "/"
  # skipOpen determines whether to automatically open the webui on startup
  skipOpen: false

# datastore represents the specs cloudgrep uses for creating and/or connecting to the datastore/database used.
datastore:
  # type is the kind of datastore to be used by cloudgrep (currently only supports SQLite)
  type: sqlite
  #  skipRefresh determines whether to refresh the data (i.e. scan the cloud) on startup.
  skipRefresh: false
  # dataSourceName is the Type-specific data source name or uri for connecting to the desired data source
  # default: use memory DB - no data stored locally
  dataSourceName: "file::memory:?cache=shared"
  # use a file DB - the data is persisted on your disk
  # dataSourceName: "~/cloudgrep_data.db"

# providers represents the cloud providers cloudgrep will scan w/ the current credentials
providers:
  - cloud: aws # cloud is the type of the cloud provider (currently only AWS is supported)
    # regions is the list of different regions within the cloud provider to scan
    # default: use the default AWS region set in your terminal
    # ex: use one region
    # regions: [us-east-1]
    # ex: use one region + global some resources like S3 Bucket are not region specific
    # regions: [us-east-1, global]
    # ex: use "all" region to scan all available regions
    # regions: [all]