name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO_VERSION: 1.18
  CGO_ENABLED: 0

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go mod download
      - run: make test
        env:
          CGO_ENABLED: 1
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.out
          token: ${{ secrets.CLOUDGREP_CODECOV_TOKEN }}
          fail_ci_if_error: true

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go mod download
      - run: script/check_formatting.sh

  mod_tidy_check:
    name: mod_tidy_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go mod download
      - run: go mod tidy -go=${{ env.GO_VERSION }}
      - name: "Check go.mod and go.sum changed"
        run: |
          export go_mod_changed=$(git status | grep go.mod | wc -l | tr -d ' ')
          if [[ $go_mod_changed -gt 0 ]]; then exit 1; fi
          export go_sum_changed=$(git status | grep go.sum | wc -l | tr -d ' ')
          if [[ $go_sum_changed -gt 0 ]]; then exit 1; fi
