on:
  push:
    # branches:
    # - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm install env-cmd -g
      working-directory: ./fe
    - name: Install project dependencies
      working-directory: ./fe
      run: npm ci
    - name: Builds the app for production
      working-directory: ./fe
      run: npm run build
    - name: Replace the static assets
      working-directory: ./static
      run: |
        rm -rf ./css ./js *.ico *.html *.txt *.json *.png
        cp -r ../fe/build/static/css .
        cp -r ../fe/build/static/js .
        cp ../fe/build/*.ico .
        cp ../fe/build/*.html .
        cp ../fe/build/*.txt .
        cp ../fe/build/*.json .
        cp ../fe/build/*.png .
