name: Load Test

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "loadtest/**"
      - "pkg/datastore/**"
  push:
    branches:
      - main

env:
  GO_VERSION: 1.18
  CGO_ENABLED: 0

permissions:
  contents: read

jobs:
  go-load-test:
    name: go load test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go mod download
      - run: make load-test
        env:
          CGO_ENABLED: 1
