name: markdown-autodocs

on:
  push:
    # branches:
    #   - '**'

jobs:
  auto-update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.4
        with:
          commit_message: 'docs: Update README.md'
