name: Release

on:
  push:
    # TODO Build and publish artifacts for a release
    # tags:
    #   - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # - name: Log into GitHub Container Registry
      #   run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${GITHUB_ACTOR,,} --password-stdin

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install all necessary dependencies
        run: make setup

      - name: Build Release Artifacts
        run: make release

      - name: set release name
        run: |
          # remove slashes since they aren't valid in filenames
          no_slash_ref_name=$(echo $GITHUB_REF_NAME | sed -E 's/\//-/g')
          echo "release_name=$no_slash_ref_name" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.release_name }}
          path: bin/*.zip
