name: Test-Release

on:
  push:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      run: |
        sudo curl -LO https://go.dev/dl/go1.18.darwin-amd64.tar.gz
        sudo rm -rf /usr/local/go
        sudo tar -C /usr/local -xzf go1.18.darwin-amd64.tar.gz
        sudo mv /usr/local/go/bin/go /usr/local/bin/go
        sudo mv /usr/local/go/bin/gofmt /usr/local/bin/gofmt

    - name: Build Mac OS ARM64
      if: "!steps.bumpr.outputs.skip"
      id: build
      run: |
        release-darwin-arm64
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: cloudgrep_darwin_arm64
        path: ./bin/cloudgrep_darwin_arm64

  build-ubuntu:
    needs: [build-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/download-artifact@v2
      with:
        name: cloudgrep_darwin_arm64
    - run: ls -lh .
