name: Release

on:
  push:
    # TODO Build and publish artifacts for a release
    # tags:
    #   - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # - name: Log into GitHub Container Registry
      #   run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${GITHUB_ACTOR,,} --password-stdin

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install all necessary dependencies
        run: make setup

      - name: Build Release Artifacts
        run: make release

      - uses: actions/upload-artifact@v2
        with:
          name: release-${{ github.ref_name }}
          name: Binaries
          path: bin/*.zip
