name: Release

on:
  push:
    # TODO Build and publish artifacts for a release
    # branches:
    #   - main
    # tags:
    #   - "v*.*.*"

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.url }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3


      # Bump version on merging Pull Requests with specific labels.
      # (bump:major,bump:minor,bump:patch)
      - id: bumpr
        # TODO uncomment before merge to main
        # if: "!startsWith(github.ref, 'refs/tags/')"
        uses: haya14busa/action-bumpr@v1
        
      # Update corresponding major and minor tag.
      # e.g. Update v1 and v1.2 when releasing v1.2.3
      - uses: haya14busa/action-update-semver@v1
        # TODO uncomment before merge to main
        # if: "!steps.bumpr.outputs.skip"
        with:
          tag: ${{ steps.bumpr.outputs.next_version }}

      # Get tag name
      - id: tag
        uses: haya14busa/action-cond@v1
        with:
          cond: "${{ startsWith(github.ref, 'refs/tags/') }}"
          if_true: ${{ github.ref }}
          if_false: ${{ steps.bumpr.outputs.next_version }}
    
      - name: Set up Go
        # TODO uncomment before merge to main
        # if: "!steps.bumpr.outputs.skip"
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build Release Artifacts
        # TODO uncomment before merge to main
        # if: "!steps.bumpr.outputs.skip"
        id: build
        run: |
          make setup
          make release

      - name: Create Release
        # TODO uncomment before merge to main
        # if: "!steps.bumpr.outputs.skip"
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.build.outputs.VERSION }}
          # TODO remove
          prerelease: true
          generate_release_notes: true
          files: |
            ./bin/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
      - name: Update version file
        # TODO uncomment before merge to main
        # if: "!steps.bumpr.outputs.skip"
        uses: pocket-apps/action-update-version@v1
        with:
          files: 'pkg/command/version.go'
          version-regexp: '\d+.\d+.\d+'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
