name: Test-Release

on:
  push:

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.url }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        if: "!steps.bumpr.outputs.skip"
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install GCC and SQLite for Arm64
        uses: ryankurte/action-apt@v0.3.0
        with:
          arch: arm64
          packages: "gcc-10-aarch64-linux-gnu gcc-aarch64-linux-gnu libsqlite3-dev:arm64"
          
      - name: Build Release Artifacts
        if: "!steps.bumpr.outputs.skip"
        id: build
        run: |
          make setup
          VERSION=${{ steps.tag.outputs.value }} make release
