name: Release

on:
  push:

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.url }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        if: "!steps.bumpr.outputs.skip"
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build Release Artifacts
        if: "!steps.bumpr.outputs.skip"
        id: build
        run: |
          make setup
          VERSION=${{ steps.tag.outputs.value }} make release
