name: Test-Release

on:
  push:

jobs:
  bumpr:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.bumpr.outputs.skip }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Bump version on merging Pull Requests with specific labels.
    # (bump:major,bump:minor,bump:patch)
    - name: Bump version on merging PR
      id: bumpr
      if: "!startsWith(github.ref, 'refs/tags/')"
      uses: haya14busa/action-bumpr@v1

  build-macos-arm64:
    name: Build macOS ARM 64
    needs: [bumpr]
    if: "!needs.bumpr.outputs.skip"
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
