name: Test-Release

on:
  push:

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      run: |
        sudo curl -LO https://go.dev/dl/go1.18.darwin-amd64.tar.gz
        sudo rm -rf /usr/local/go
        sudo tar -C /usr/local -xzf go1.18.darwin-amd64.tar.gz
        sudo mv /usr/local/go/bin/go /usr/local/bin/go
        sudo mv /usr/local/go/bin/gofmt /usr/local/bin/gofmt

    - name: Build Mac OS
      id: build
      run: |
        make release-darwin

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: cloudgrep_darwin
        path: ./bin/*.zip

  release:
    name: Create release
    needs: [macos-latest]
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # retrieve the darwin arm64 binary build in previous job
    - uses: actions/download-artifact@v2
      with:
        name: cloudgrep_darwin
    - run: |
          tar xvf cloudgrep_darwin.zip
          mkdir ./bin
          cp *.zip ./bin/
          ls -l ./bin/
